backend:
  name: github
  repo: rebelivious-creative/CrossField-Collective
  branch: main

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "website_content"
    label: "Website Content"
    files:
      - label: "Edit Homepage"
        name: "home"
        file: "content.json"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_sub", widget: "text"}
          - {label: "About Text", name: "about_text", widget: "text"}
